'use client';

import { useState } from 'react';
import Link from 'next/link';
import CommonHeader from '../../../components/CommonHeader';
import Footer from '../../../components/Footer';
import { FaPlus, FaTrash, FaCalculator, FaDownload, FaRedo } from 'react-icons/fa';

export default function RecipeCostCalculatorClient() {
  const [recipeName, setRecipeName] = useState('');
  const [servings, setServings] = useState(1);
  const [targetFoodCost, setTargetFoodCost] = useState(30);
  const [ingredients, setIngredients] = useState([
    { id: 1, name: '', quantity: '', unit: 'g', pricePerUnit: '', totalCost: 0 }
  ]);
  const [calculated, setCalculated] = useState(false);

  const units = ['g', 'kg', 'ml', 'L', 'pcs', 'tbsp', 'tsp', 'cup'];

  const addIngredient = () => {
    setIngredients([...ingredients, {
      id: Date.now(),
      name: '',
      quantity: '',
      unit: 'g',
      pricePerUnit: '',
      totalCost: 0
    }]);
  };

  const removeIngredient = (id) => {
    if (ingredients.length > 1) {
      setIngredients(ingredients.filter(ing => ing.id !== id));
    }
  };

  const updateIngredient = (id, field, value) => {
    setIngredients(ingredients.map(ing => {
      if (ing.id === id) {
        const updated = { ...ing, [field]: value };
        if (field === 'quantity' || field === 'pricePerUnit') {
          const qty = parseFloat(updated.quantity) || 0;
          const price = parseFloat(updated.pricePerUnit) || 0;
          updated.totalCost = qty * price;
        }
        return updated;
      }
      return ing;
    }));
    setCalculated(false);
  };

  const totalRecipeCost = ingredients.reduce((sum, ing) => sum + (ing.totalCost || 0), 0);
  const costPerServing = servings > 0 ? totalRecipeCost / servings : 0;
  const idealSellingPrice = targetFoodCost > 0 ? costPerServing / (targetFoodCost / 100) : 0;
  const suggestedPrices = {
    low: idealSellingPrice * 0.9,
    mid: idealSellingPrice,
    high: idealSellingPrice * 1.2
  };

  const handleCalculate = () => {
    setCalculated(true);
  };

  const handleReset = () => {
    setRecipeName('');
    setServings(1);
    setTargetFoodCost(30);
    setIngredients([{ id: 1, name: '', quantity: '', unit: 'g', pricePerUnit: '', totalCost: 0 }]);
    setCalculated(false);
  };

  const handleDownload = () => {
    const content = `
RECIPE COST ANALYSIS
====================
Recipe: ${recipeName || 'Unnamed Recipe'}
Servings: ${servings}
Target Food Cost: ${targetFoodCost}%

INGREDIENTS:
${ingredients.map(ing => `- ${ing.name}: ${ing.quantity} ${ing.unit} @ ₹${ing.pricePerUnit}/${ing.unit} = ₹${ing.totalCost.toFixed(2)}`).join('\n')}

SUMMARY:
Total Recipe Cost: ₹${totalRecipeCost.toFixed(2)}
Cost Per Serving: ₹${costPerServing.toFixed(2)}
Ideal Selling Price: ₹${idealSellingPrice.toFixed(2)}

SUGGESTED MENU PRICES:
Budget: ₹${suggestedPrices.low.toFixed(0)}
Standard: ₹${suggestedPrices.mid.toFixed(0)}
Premium: ₹${suggestedPrices.high.toFixed(0)}

Generated by DineOpen Recipe Cost Calculator
https://www.dineopen.com/tools/recipe-cost-calculator
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${recipeName || 'recipe'}-cost-analysis.txt`;
    a.click();
  };

  return (
    <>
      <CommonHeader />
      <div style={{ minHeight: '100vh', backgroundColor: '#f9fafb', paddingTop: '80px' }}>
        {/* Hero */}
        <section style={{ background: 'linear-gradient(135deg, #059669 0%, #047857 100%)', color: 'white', padding: '60px 20px', textAlign: 'center' }}>
          <div style={{ maxWidth: '800px', margin: '0 auto' }}>
            <h1 style={{ fontSize: '36px', fontWeight: '800', marginBottom: '16px' }}>Recipe Cost Calculator</h1>
            <p style={{ fontSize: '18px', opacity: 0.95 }}>
              Calculate dish costs, food cost percentage, and find the ideal menu price for profitability.
            </p>
          </div>
        </section>

        {/* Calculator */}
        <section style={{ padding: '60px 20px' }}>
          <div style={{ maxWidth: '900px', margin: '0 auto' }}>
            <div style={{ backgroundColor: 'white', borderRadius: '16px', padding: '32px', boxShadow: '0 4px 20px rgba(0,0,0,0.08)' }}>
              {/* Recipe Info */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px', marginBottom: '32px' }}>
                <div>
                  <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: '#374151', marginBottom: '8px' }}>Recipe Name</label>
                  <input
                    type="text"
                    value={recipeName}
                    onChange={(e) => setRecipeName(e.target.value)}
                    placeholder="e.g., Butter Chicken"
                    style={{ width: '100%', padding: '12px', border: '1px solid #d1d5db', borderRadius: '8px', fontSize: '15px' }}
                  />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: '#374151', marginBottom: '8px' }}>Number of Servings</label>
                  <input
                    type="number"
                    value={servings}
                    onChange={(e) => { setServings(parseInt(e.target.value) || 1); setCalculated(false); }}
                    min="1"
                    style={{ width: '100%', padding: '12px', border: '1px solid #d1d5db', borderRadius: '8px', fontSize: '15px' }}
                  />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: '#374151', marginBottom: '8px' }}>Target Food Cost %</label>
                  <input
                    type="number"
                    value={targetFoodCost}
                    onChange={(e) => { setTargetFoodCost(parseInt(e.target.value) || 30); setCalculated(false); }}
                    min="1"
                    max="100"
                    style={{ width: '100%', padding: '12px', border: '1px solid #d1d5db', borderRadius: '8px', fontSize: '15px' }}
                  />
                </div>
              </div>

              {/* Ingredients Table */}
              <div style={{ marginBottom: '24px' }}>
                <h3 style={{ fontSize: '18px', fontWeight: '700', color: '#111827', marginBottom: '16px' }}>Ingredients</h3>
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: '600px' }}>
                    <thead>
                      <tr style={{ backgroundColor: '#f3f4f6' }}>
                        <th style={{ padding: '12px', textAlign: 'left', fontSize: '13px', fontWeight: '600' }}>Ingredient</th>
                        <th style={{ padding: '12px', textAlign: 'center', fontSize: '13px', fontWeight: '600', width: '100px' }}>Quantity</th>
                        <th style={{ padding: '12px', textAlign: 'center', fontSize: '13px', fontWeight: '600', width: '80px' }}>Unit</th>
                        <th style={{ padding: '12px', textAlign: 'center', fontSize: '13px', fontWeight: '600', width: '120px' }}>Price/Unit (₹)</th>
                        <th style={{ padding: '12px', textAlign: 'right', fontSize: '13px', fontWeight: '600', width: '100px' }}>Cost (₹)</th>
                        <th style={{ padding: '12px', width: '50px' }}></th>
                      </tr>
                    </thead>
                    <tbody>
                      {ingredients.map((ing, idx) => (
                        <tr key={ing.id} style={{ borderBottom: '1px solid #e5e7eb' }}>
                          <td style={{ padding: '8px' }}>
                            <input
                              type="text"
                              value={ing.name}
                              onChange={(e) => updateIngredient(ing.id, 'name', e.target.value)}
                              placeholder="e.g., Chicken"
                              style={{ width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '6px', fontSize: '14px' }}
                            />
                          </td>
                          <td style={{ padding: '8px' }}>
                            <input
                              type="number"
                              value={ing.quantity}
                              onChange={(e) => updateIngredient(ing.id, 'quantity', e.target.value)}
                              placeholder="500"
                              style={{ width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '6px', fontSize: '14px', textAlign: 'center' }}
                            />
                          </td>
                          <td style={{ padding: '8px' }}>
                            <select
                              value={ing.unit}
                              onChange={(e) => updateIngredient(ing.id, 'unit', e.target.value)}
                              style={{ width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '6px', fontSize: '14px' }}
                            >
                              {units.map(u => <option key={u} value={u}>{u}</option>)}
                            </select>
                          </td>
                          <td style={{ padding: '8px' }}>
                            <input
                              type="number"
                              value={ing.pricePerUnit}
                              onChange={(e) => updateIngredient(ing.id, 'pricePerUnit', e.target.value)}
                              placeholder="0.50"
                              step="0.01"
                              style={{ width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '6px', fontSize: '14px', textAlign: 'center' }}
                            />
                          </td>
                          <td style={{ padding: '8px', textAlign: 'right', fontWeight: '600', color: '#059669' }}>
                            ₹{ing.totalCost.toFixed(2)}
                          </td>
                          <td style={{ padding: '8px', textAlign: 'center' }}>
                            <button
                              onClick={() => removeIngredient(ing.id)}
                              style={{ padding: '8px', backgroundColor: '#fee2e2', color: '#dc2626', border: 'none', borderRadius: '6px', cursor: 'pointer' }}
                            >
                              <FaTrash size={12} />
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                <button
                  onClick={addIngredient}
                  style={{ marginTop: '16px', display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 20px', backgroundColor: '#f3f4f6', color: '#374151', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '14px', fontWeight: '500' }}
                >
                  <FaPlus size={12} /> Add Ingredient
                </button>
              </div>

              {/* Action Buttons */}
              <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
                <button
                  onClick={handleCalculate}
                  style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '14px 28px', backgroundColor: '#059669', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '16px', fontWeight: '600' }}
                >
                  <FaCalculator /> Calculate Cost
                </button>
                <button
                  onClick={handleReset}
                  style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '14px 28px', backgroundColor: '#f3f4f6', color: '#374151', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '16px', fontWeight: '500' }}
                >
                  <FaRedo /> Reset
                </button>
              </div>

              {/* Results */}
              {calculated && totalRecipeCost > 0 && (
                <div style={{ marginTop: '32px', padding: '24px', backgroundColor: '#ecfdf5', borderRadius: '12px' }}>
                  <h3 style={{ fontSize: '20px', fontWeight: '700', color: '#065f46', marginBottom: '20px' }}>Cost Analysis</h3>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '20px', marginBottom: '24px' }}>
                    <div style={{ padding: '16px', backgroundColor: 'white', borderRadius: '10px', textAlign: 'center' }}>
                      <p style={{ fontSize: '14px', color: '#6b7280', marginBottom: '4px' }}>Total Recipe Cost</p>
                      <p style={{ fontSize: '28px', fontWeight: '800', color: '#059669' }}>₹{totalRecipeCost.toFixed(2)}</p>
                    </div>
                    <div style={{ padding: '16px', backgroundColor: 'white', borderRadius: '10px', textAlign: 'center' }}>
                      <p style={{ fontSize: '14px', color: '#6b7280', marginBottom: '4px' }}>Cost Per Serving</p>
                      <p style={{ fontSize: '28px', fontWeight: '800', color: '#059669' }}>₹{costPerServing.toFixed(2)}</p>
                    </div>
                    <div style={{ padding: '16px', backgroundColor: 'white', borderRadius: '10px', textAlign: 'center' }}>
                      <p style={{ fontSize: '14px', color: '#6b7280', marginBottom: '4px' }}>Ideal Selling Price</p>
                      <p style={{ fontSize: '28px', fontWeight: '800', color: '#059669' }}>₹{idealSellingPrice.toFixed(0)}</p>
                      <p style={{ fontSize: '12px', color: '#6b7280' }}>at {targetFoodCost}% food cost</p>
                    </div>
                  </div>

                  <div style={{ padding: '16px', backgroundColor: 'white', borderRadius: '10px', marginBottom: '20px' }}>
                    <h4 style={{ fontSize: '14px', fontWeight: '600', color: '#374151', marginBottom: '12px' }}>Suggested Menu Prices</h4>
                    <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
                      <div style={{ padding: '12px 20px', backgroundColor: '#dbeafe', borderRadius: '8px' }}>
                        <p style={{ fontSize: '12px', color: '#1e40af' }}>Budget ({Math.round(targetFoodCost * 1.1)}% cost)</p>
                        <p style={{ fontSize: '20px', fontWeight: '700', color: '#1e40af' }}>₹{suggestedPrices.low.toFixed(0)}</p>
                      </div>
                      <div style={{ padding: '12px 20px', backgroundColor: '#d1fae5', borderRadius: '8px' }}>
                        <p style={{ fontSize: '12px', color: '#065f46' }}>Standard ({targetFoodCost}% cost)</p>
                        <p style={{ fontSize: '20px', fontWeight: '700', color: '#065f46' }}>₹{suggestedPrices.mid.toFixed(0)}</p>
                      </div>
                      <div style={{ padding: '12px 20px', backgroundColor: '#fef3c7', borderRadius: '8px' }}>
                        <p style={{ fontSize: '12px', color: '#92400e' }}>Premium ({Math.round(targetFoodCost * 0.83)}% cost)</p>
                        <p style={{ fontSize: '20px', fontWeight: '700', color: '#92400e' }}>₹{suggestedPrices.high.toFixed(0)}</p>
                      </div>
                    </div>
                  </div>

                  <button
                    onClick={handleDownload}
                    style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '12px 24px', backgroundColor: '#059669', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '14px', fontWeight: '600' }}
                  >
                    <FaDownload /> Download Analysis
                  </button>
                </div>
              )}
            </div>
          </div>
        </section>

        {/* Tips Section */}
        <section style={{ padding: '60px 20px', backgroundColor: 'white' }}>
          <div style={{ maxWidth: '800px', margin: '0 auto' }}>
            <h2 style={{ fontSize: '28px', fontWeight: '700', color: '#111827', marginBottom: '32px', textAlign: 'center' }}>Food Costing Tips</h2>
            <div style={{ display: 'grid', gap: '16px' }}>
              {[
                { title: 'Target 28-32% food cost', desc: 'Most profitable restaurants maintain food costs between 28-32% of menu price.' },
                { title: 'Account for waste', desc: 'Add 5-10% to ingredient costs to account for prep waste, spoilage, and portion variance.' },
                { title: 'Update costs regularly', desc: 'Ingredient prices fluctuate. Review recipe costs monthly to maintain margins.' },
                { title: 'Consider all costs', desc: 'Include garnishes, sauces, and sides. Small items add up quickly.' },
              ].map((tip, idx) => (
                <div key={idx} style={{ padding: '20px', backgroundColor: '#f9fafb', borderRadius: '12px', borderLeft: '4px solid #059669' }}>
                  <h3 style={{ fontSize: '16px', fontWeight: '600', color: '#111827', marginBottom: '4px' }}>{tip.title}</h3>
                  <p style={{ fontSize: '14px', color: '#6b7280' }}>{tip.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section style={{ padding: '60px 20px', backgroundColor: '#059669', color: 'white', textAlign: 'center' }}>
          <div style={{ maxWidth: '600px', margin: '0 auto' }}>
            <h2 style={{ fontSize: '28px', fontWeight: '700', marginBottom: '16px' }}>Automate Your Food Costing</h2>
            <p style={{ fontSize: '16px', opacity: 0.95, marginBottom: '24px' }}>DineOpen tracks recipe costs automatically as ingredient prices change.</p>
            <Link href="https://dineopen.com/login" style={{ display: 'inline-block', padding: '14px 32px', backgroundColor: 'white', color: '#059669', borderRadius: '8px', fontWeight: '700', textDecoration: 'none' }}>
              Start Free Trial
            </Link>
          </div>
        </section>
      </div>
      <Footer />
    </>
  );
}
