// AUTO-GENERATED brand/liquor image keyword map.
// Real product photos downloaded (free, web sources) into public/placeholder-images/liquor/.
// Consumed by placeholderImages.js — merged into the keyword index (longest-match-first).
// Benefits every restaurant bar menu, not just the one it was seeded from.
export const LIQUOR_KEYWORD_MAP = [
  [["plain peanut"], "liquor/plain-peanut.jpg"],
  [["jameson irish whiskey"], "liquor/jameson-irish-whiskey.jpg"],
  [["jameson black barrel"], "liquor/jameson-black-barrel.jpg"],
  [["smirnoff black ice"], "liquor/smirnoff-black-ice.jpg"],
  [["pilsner lager"], "liquor/pilsner-lager.jpg"],
  [["tusker lager"], "liquor/tusker-lager.jpg"],
  [["tusker lite"], "liquor/tusker-lite.jpg"],
  [["tusker malt"], "liquor/tusker-malt.jpg"],
  [["tusker cider"], "liquor/tusker-cider.jpg"],
  [["tusker premium"], "liquor/tusker-premium.jpg"],
  [["white cap lager"], "liquor/white-cap-lager.jpg"],
  [["white cap light"], "liquor/white-cap-light.jpg"],
  [["snapp"], "liquor/snapp.jpg"],
  [["guiness kubwa"], "liquor/guiness-kubwa.jpg"],
  [["guiness smooth"], "liquor/guiness-smooth.jpg"],
  [["balozi"], "liquor/balozi.jpg"],
  [["heineken"], "liquor/heineken.jpg"],
  [["heineken zero"], "liquor/heineken-zero.jpg"],
  [["hunters dry"], "liquor/hunters-dry.jpg"],
  [["corona extra"], "liquor/corona-extra.jpg"],
  [["pineapple punch beer"], "liquor/pineapple-punch-beer.jpg"],
  [["desparado"], "liquor/desparado.jpg"],
  [["savannah cider"], "liquor/savannah-cider.jpg"],
  [["bila shaka"], "liquor/bila-shaka.jpg"],
  [["capitan"], "liquor/capitan.jpg"],
  [["sultan"], "liquor/sultan.jpg"],
  [["dire straits"], "liquor/dire-straits.jpg"],
  [["mango juice"], "liquor/mango-juice.jpg"],
  [["orange juice"], "liquor/orange-juice.jpg"],
  [["passion juice"], "liquor/passion-juice.jpg"],
  [["pineapple juice"], "liquor/pineapple-juice.jpg"],
  [["pineapple mint juice"], "liquor/pineapple-mint-juice.jpg"],
  [["coke regular"], "liquor/coke-regular.jpg"],
  [["coke zero"], "liquor/coke-zero.jpg"],
  [["sprite"], "liquor/sprite.jpg"],
  [["fanta black currant"], "liquor/fanta-black-currant.jpg"],
  [["fanta orange"], "liquor/fanta-orange.jpg"],
  [["ginger ale"], "liquor/ginger-ale.jpg"],
  [["bitter lemon"], "liquor/bitter-lemon.jpg"],
  [["stoney"], "liquor/stoney.jpg"],
  [["pepsi regular"], "liquor/pepsi-regular.jpg"],
  [["7 up"], "liquor/7-up.jpg"],
  [["miranda orange"], "liquor/miranda-orange.jpg"],
  [["miranda pineapple"], "liquor/miranda-pineapple.jpg"],
  [["miranda green apple"], "liquor/miranda-green-apple.jpg"],
  [["miranda lemon"], "liquor/miranda-lemon.jpg"],
  [["miranda fruity"], "liquor/miranda-fruity.jpg"],
  [["mountain dew"], "liquor/mountain-dew.jpg"],
  [["evervess club soda"], "liquor/evervess-club-soda.jpg"],
  [["evervess tonic water"], "liquor/evervess-tonic-water.jpg"],
  [["soda water"], "liquor/soda-water.jpg"],
  [["tonic water"], "liquor/tonic-water.jpg"],
  [["mineral still water"], "liquor/mineral-still-water.jpg"],
  [["sparkling water"], "liquor/sparkling-water.jpg"],
  [["red bull regular"], "liquor/red-bull-regular.jpg"],
  [["del monte juice"], "liquor/del-monte-juice.jpg"],
  [["pierre marcel sweet red"], "liquor/pierre-marcel-sweet-red.jpg"],
  [["four cousins sweet red"], "liquor/four-cousins-sweet-red.jpg"],
  [["dh premier grand cru"], "liquor/dh-premier-grand-cru.jpg"],
  [["vondeling merlot red"], "liquor/vondeling-merlot-red.jpg"],
  [["el chivo merlot"], "liquor/el-chivo-merlot.jpg"],
  [["delush sweet red"], "liquor/delush-sweet-red.jpg"],
  [["leopards leap cabernet sauvignon"], "liquor/leopards-leap-cabernet-sauvignon.jpg"],
  [["nederburg sauvignon red dry"], "liquor/nederburg-sauvignon-red-dry.jpg"],
  [["vondeling chenin blanc"], "liquor/vondeling-chenin-blanc.jpg"],
  [["pierre marcel sweet white"], "liquor/pierre-marcel-sweet-white.jpg"],
  [["four cousins sweet white"], "liquor/four-cousins-sweet-white.jpg"],
  [["delush sweet white"], "liquor/delush-sweet-white.jpg"],
  [["leopards leap chenin blanc"], "liquor/leopards-leap-chenin-blanc.jpg"],
  [["nederburg sauvignon blanc"], "liquor/nederburg-sauvignon-blanc.jpg"],
  [["four cousins rose"], "liquor/four-cousins-rose.jpg"],
  [["vondeling rose"], "liquor/vondeling-rose.jpg"],
  [["delush rose"], "liquor/delush-rose.jpg"],
  [["embassy light"], "liquor/embassy-light.jpg"],
  [["dunhill swift"], "liquor/dunhill-swift.jpg"],
  [["kamiki"], "liquor/kamiki.jpg"],
  [["nikka super"], "liquor/nikka-super.jpg"],
  [["jw black label"], "liquor/jw-black-label.jpg"],
  [["jw double black label"], "liquor/jw-double-black-label.jpg"],
  [["jw gold label"], "liquor/jw-gold-label.jpg"],
  [["jw red label"], "liquor/jw-red-label.jpg"],
  [["glenfiddich 12 year"], "liquor/glenfiddich-12-year.jpg"],
  [["glenfiddich 15 year"], "liquor/glenfiddich-15-year.jpg"],
  [["glenfiddich 18 year"], "liquor/glenfiddich-18-year.jpg"],
  [["glenlivet 12 year"], "liquor/glenlivet-12-year.jpg"],
  [["glenlivet 15 year"], "liquor/glenlivet-15-year.jpg"],
  [["glenlivet 18 year"], "liquor/glenlivet-18-year.jpg"],
  [["glenlivet founders reserve"], "liquor/glenlivet-founders-reserve.jpg"],
  [["glenkinchie 12 year"], "liquor/glenkinchie-12-year.jpg"],
  [["famous grouse"], "liquor/famous-grouse.jpg"],
  [["jim bean"], "liquor/jim-bean.jpg"],
  [["jack daniels"], "liquor/jack-daniels.jpg"],
  [["jack daniels honey"], "liquor/jack-daniels-honey.jpg"],
  [["gentleman jack"], "liquor/gentleman-jack.jpg"],
  [["grants"], "liquor/grants.jpg"],
  [["chivas regal 12 year"], "liquor/chivas-regal-12-year.jpg"],
  [["chivas regal 18 year"], "liquor/chivas-regal-18-year.jpg"],
  [["balentines"], "liquor/balentines.jpg"],
  [["money shoulder"], "liquor/money-shoulder.jpg"],
  [["southern comfort"], "liquor/southern-comfort.jpg"],
  [["singleton 12 year"], "liquor/singleton-12-year.jpg"],
  [["singleton 15 year"], "liquor/singleton-15-year.jpg"],
  [["talisker"], "liquor/talisker.jpg"],
  [["dh premier grand cru dry"], "liquor/dh-premier-grand-cru-dry.jpg"],
  [["dh red claret dry"], "liquor/dh-red-claret-dry.jpg"],
  [["cellar cask red sweet"], "liquor/cellar-cask-red-sweet.jpg"],
  [["cellar cask white sweet"], "liquor/cellar-cask-white-sweet.jpg"],
  [["smirnoff vodka red"], "liquor/smirnoff-vodka-red.jpg"],
  [["absolute vodka"], "liquor/absolute-vodka.jpg"],
  [["grey goose"], "liquor/grey-goose.jpg"],
  [["kettle one"], "liquor/kettle-one.jpg"],
  [["ciroc vodka"], "liquor/ciroc-vodka.jpg"],
  [["bombay sapphire"], "liquor/bombay-sapphire.jpg"],
  [["gordons gin"], "liquor/gordons-gin.jpg"],
  [["beefeater clear"], "liquor/beefeater-clear.jpg"],
  [["beefeater pink"], "liquor/beefeater-pink.jpg"],
  [["hendricks"], "liquor/hendricks.jpg"],
  [["gilbeys gin"], "liquor/gilbey-s-gin.jpg"],
  [["tanqueray dry"], "liquor/tanqueray-dry.jpg"],
  [["tanqueray 10 gin"], "liquor/tanqueray-10-gin.jpg"],
  [["tanqueray servilla"], "liquor/tanqueray-servilla.jpg"],
  [["procera"], "liquor/procera.jpg"],
  [["greenalls pink"], "liquor/greenalls-pink.jpg"],
  [["bacardi"], "liquor/bacardi.jpg"],
  [["captain morgan spices"], "liquor/captain-morgan-spices.jpg"],
  [["captain morgan dark"], "liquor/captain-morgan-dark.jpg"],
  [["old monk"], "liquor/old-monk.jpg"],
  [["myers rum"], "liquor/myers-rum.jpg"],
  [["mailibu coconut rum"], "liquor/mailibu-coconut-rum.jpg"],
  [["jaggermister"], "liquor/jaggermister.jpg"],
  [["zappa"], "liquor/zappa.jpg"],
  [["apple sour"], "liquor/apple-sour.jpg"],
  [["amarula"], "liquor/amarula.jpg"],
  [["baileys"], "liquor/bailey-s.jpg"],
  [["kahula"], "liquor/kahula.jpg"],
  [["blue caracao"], "liquor/blue-caracao.jpg"],
  [["limancello"], "liquor/limancello.jpg"],
  [["tripple sec"], "liquor/tripple-sec.jpg"],
  [["jose cuevo silver"], "liquor/jose-cuevo-silver.jpg"],
  [["jose cuevo gold"], "liquor/jose-cuevo-gold.jpg"],
  [["camino gold"], "liquor/camino-gold.jpg"],
  [["camino clear"], "liquor/camino-clear.jpg"],
  [["don julio reposado"], "liquor/don-julio-reposado.jpg"],
  [["don julio blanco"], "liquor/don-julio-blanco.jpg"],
  [["viceroy"], "liquor/viceroy.jpg"],
  [["richot"], "liquor/richot.jpg"],
  [["hennesey vsop"], "liquor/hennesey-vsop.jpg"],
  [["hennesey vs"], "liquor/hennesey-vs.jpg"],
  [["martel vssd"], "liquor/martel-vssd.jpg"],
  [["manyatta pineapple"], "liquor/manyatta-pineapple.jpg"],
  [["canadian club"], "liquor/canadian-club.jpg"],
];
